package github

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/eyupio/zoomies/internal/aicontext"
)

func TestContextPublicationVerifiesOriginalGitBlobsRatherThanSelfReportedHashes(t *testing.T) {
	fake, client := migrationFake(t)
	fake.AddFile("acme/widgets", "src/main.go", "package widgets\n")
	source, err := client.(ContextSetupClient).ReadContextSetup(t.Context(), "acme/widgets", "main")
	if err != nil {
		t.Fatal(err)
	}
	cfg := aicontext.DefaultConfig("main")
	hash, _ := cfg.Hash()
	snapshot := aicontext.Snapshot{Manifest: aicontext.Manifest{SchemaVersion: 1, Repository: aicontext.RepositoryKey{GitHubHost: "github.com", InstallationID: "1", RepositoryID: source.Repository.ID}, SourceBranch: "main", SourceCommit: source.Commit, ConfigHash: hash, GeneratedAt: time.Now(), Manager: "zoomies", Generator: "repomix@1.18.1"}, Files: []aicontext.File{{Path: "src/main.go", Content: "package widgets\n", SHA256: aicontext.Hash([]byte("package widgets\n"))}}}
	publish := func(extra bool) {
		body, _ := json.Marshal(snapshot)
		manifest, _ := json.Marshal(map[string]string{"snapshot_sha256": aicontext.Hash(body)})
		files := map[string]string{aicontext.OutputDirectory + "/snapshot.json": string(body), aicontext.OutputDirectory + "/manifest.json": string(manifest), aicontext.OutputDirectory + "/NOTICE.md": "Managed by Zoomies AI Context. Generated by Repomix. Do not edit.\n"}
		if extra {
			files["unexpected.go"] = "package injected"
		}
		fake.SetContextBranch("acme/widgets", aicontext.OutputBranch, files)
	}
	ingestion := client.(ContextIngestionClient)
	publish(false)
	if _, err := ingestion.ReadContextPublication(t.Context(), "acme/widgets", "main"); err != nil {
		t.Fatal(err)
	}
	snapshot.Files[0].Content = "package forged\n"
	snapshot.Files[0].SHA256 = aicontext.Hash([]byte(snapshot.Files[0].Content))
	publish(false)
	if _, err := ingestion.ReadContextPublication(t.Context(), "acme/widgets", "main"); err == nil || !strings.Contains(err.Error(), "trusted commit") {
		t.Fatalf("forgery admitted: %v", err)
	}
	snapshot.Files[0].Content = "package widgets\n"
	snapshot.Files[0].SHA256 = aicontext.Hash([]byte(snapshot.Files[0].Content))
	publish(true)
	if _, err := ingestion.ReadContextPublication(t.Context(), "acme/widgets", "main"); err == nil {
		t.Fatal("unowned file admitted")
	}
	publish(false)
	fake.SetFileMode("acme/widgets", "src/main.go", "120000")
	fake.AddFile("acme/widgets", "src/main.go", "package widgets\n")
	if _, err := ingestion.ReadContextPublication(t.Context(), "acme/widgets", "main"); err == nil {
		t.Fatal("symlink admitted")
	}
}

func TestContextSetupMergeRequiresTheReviewedBaseBranch(t *testing.T) {
	fake, client := migrationFake(t)
	setup := client.(ContextSetupClient)
	source, err := setup.ReadContextSetup(t.Context(), "acme/widgets", "main")
	if err != nil {
		t.Fatal(err)
	}
	pr, err := setup.OpenContextSetup(t.Context(), ContextSetupRequest{Repo: "acme/widgets", Base: "main", BaseCommit: source.Commit, Head: "context-merge-check", PlanHash: strings.Repeat("a", 64), Files: []aicontext.SetupChange{{Path: "AGENTS.md", Mode: "100644", Content: "guidance"}}})
	if err != nil {
		t.Fatal(err)
	}
	ingestion := client.(ContextIngestionClient)
	if merged, err := ingestion.ContextSetupMerged(t.Context(), "acme/widgets", pr.Number, "main"); err != nil || merged {
		t.Fatalf("open PR: %v %v", merged, err)
	}
	if !fake.MergeContextPull("acme/widgets", pr.Number) {
		t.Fatal("merge failed")
	}
	if merged, err := ingestion.ContextSetupMerged(t.Context(), "acme/widgets", pr.Number, "main"); err != nil || !merged {
		t.Fatalf("merged PR: %v %v", merged, err)
	}
	if merged, err := ingestion.ContextSetupMerged(t.Context(), "acme/widgets", pr.Number, "other"); err != nil || merged {
		t.Fatalf("wrong base: %v %v", merged, err)
	}
}
