"""Exercise publication boundaries without credentials or external GitHub calls."""
import base64
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import tempfile
import subprocess
import unittest
from unittest.mock import patch

spec = importlib.util.spec_from_file_location('publisher', Path(__file__).parent / 'templates' / 'publish.py')
publisher = importlib.util.module_from_spec(spec)
spec.loader.exec_module(publisher)

spec = importlib.util.spec_from_file_location('generator', Path(__file__).parent / 'templates' / 'generate.py')
generator = importlib.util.module_from_spec(spec)
spec.loader.exec_module(generator)


class SourceClassificationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        subprocess.run(['git', 'init', '-q', str(self.root)], check=True)

    def read(self, content):
        blob = subprocess.check_output(['git', '-C', str(self.root), 'hash-object', '-w', '--stdin'], input=content).decode().strip()
        return generator.source_blob(self.root, blob, len(content))

    def test_large_binary_assets_are_skipped_before_text_limits(self):
        for prefix in (b'%PDF-1.7\n\xff', b'\x89PNG\r\n\x1a\n', b'image\0'):
            self.assertIsNone(self.read(prefix + b'x' * (generator.MAX_FILE * 2)))

    def test_oversized_text_is_still_refused_without_source_in_diagnostics(self):
        with self.assertRaisesRegex(generator.GenerationRefusal, '^A source file exceeds the context size limit; add an exclusion$'):
            self.read(b'private source\n' * generator.MAX_FILE)

    def test_valid_utf8_source_preserves_exact_bytes_and_limit(self):
        content = b'a' * (generator.MAX_FILE - 2) + 'é'.encode()
        self.assertEqual(self.read(content), (content, content.decode()))
        with self.assertRaises(generator.GenerationRefusal):
            self.read(b'a' * generator.MAX_FILE + 'é'.encode())


class PublicationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.directory = Path(self.temp.name)
        self.commit = 'a' * 40
        self.identity = {'github_host': 'github.com', 'installation_id': '1', 'repository_id': 42}
        self.hash = 'b' * 64
        self.manifest = {'repository': self.identity, 'source_branch': 'main', 'source_commit': self.commit,
                         'config_hash': self.hash, 'manager': 'zoomies', 'generator': 'repomix@1.18.1', 'schema_version': 1}
        self.files = [{'path': 'main.go', 'content': 'package main\n',
                       'sha256': hashlib.sha256(b'package main\n').hexdigest()}]
        self.write_artifact()
        self.calls = []
        self.source = self.commit
        self.existing = None
        self.old_notice = None
        self.old_files = ['.zoomies/ai-context/' + n for n in ('snapshot.json', 'manifest.json', 'NOTICE.md')]

    def write_artifact(self):
        encoded = json.dumps({'manifest': self.manifest, 'files': self.files}).encode()
        (self.directory / 'snapshot.json').write_bytes(encoded)
        (self.directory / 'manifest.json').write_text(json.dumps({'snapshot_sha256': hashlib.sha256(encoded).hexdigest()}))
        (self.directory / 'NOTICE.md').write_text('Managed by Zoomies AI Context. Generated by Repomix. Do not edit.\n')

    def open(self, request, timeout=None):
        path = request.full_url.split('/repos/acme/widgets', 1)[1]
        self.calls.append((request.method, path, json.loads(request.data) if request.data else None))
        if path == '/git/ref/heads/main':
            result = {'object': {'sha': self.source}}
        elif path == '/git/ref/heads/zoomies-ai-context':
            if self.existing is None:
                import urllib.error
                raise urllib.error.HTTPError(request.full_url, 404, 'Not Found', {}, None)
            result = {'object': {'sha': self.existing}}
        elif path.startswith('/contents/'):
            result = {'encoding': 'base64', 'content': base64.b64encode(self.old_notice or b'').decode()}
        elif request.method == 'GET' and path.startswith('/git/commits/'):
            result = {'message': 'Publish Zoomies AI Context\n', 'tree': {'sha': 'tree'}}
        elif request.method == 'GET' and path.startswith('/git/trees/'):
            result = {'tree': [{'path': p, 'type': 'blob'} for p in self.old_files]}
        else:
            result = {'sha': 'c' * 40}
        return io.BytesIO(json.dumps(result).encode())

    def publish(self):
        class Opener:
            pass
        opener = Opener()
        opener.open = self.open
        with patch.object(publisher.urllib.request, 'build_opener', return_value=opener):
            publisher.publish(self.directory, 'https://api.github.test', 'acme/widgets', 'test-only-token',
                              'main', self.commit, self.identity, self.hash)

    def test_only_a_complete_valid_artifact_moves_a_ref(self):
        self.publish()
        writes = [(m, p, b) for m, p, b in self.calls if m != 'GET']
        self.assertEqual(writes[-1][1], '/git/refs')
        self.assertEqual(writes[-1][2]['ref'], 'refs/heads/zoomies-ai-context')
        tree = next(b for m, p, b in writes if p == '/git/trees')
        self.assertNotIn('base_tree', tree)
        self.assertEqual({e['path'] for e in tree['tree']}, set(self.old_files))

    def test_superseded_source_never_writes(self):
        self.source = 'd' * 40
        with self.assertRaises(ValueError):
            self.publish()
        self.assertTrue(all(m == 'GET' for m, _, _ in self.calls))

    def test_corrupt_hash_and_symlinks_never_contact_github(self):
        self.files[0]['sha256'] = 'f' * 64
        self.write_artifact()
        with self.assertRaises(ValueError):
            self.publish()
        self.assertFalse(self.calls)
        (self.directory / 'NOTICE.md').unlink()
        (self.directory / 'NOTICE.md').symlink_to('/etc/passwd')
        with self.assertRaises(ValueError):
            self.publish()
        self.assertFalse(self.calls)

    def test_existing_user_files_and_unowned_branches_are_preserved(self):
        self.existing = 'e' * 40
        self.old_notice = b'User branch'
        with self.assertRaises(ValueError):
            self.publish()
        self.assertTrue(all(m == 'GET' for m, _, _ in self.calls))
        self.calls.clear()
        self.old_notice = (self.directory / 'NOTICE.md').read_bytes()
        self.old_files.append('user.txt')
        with self.assertRaises(ValueError):
            self.publish()
        self.assertTrue(all(m == 'GET' for m, _, _ in self.calls))

    def test_existing_generated_branch_moves_without_force(self):
        self.existing = 'e' * 40
        self.old_notice = (self.directory / 'NOTICE.md').read_bytes()
        self.publish()
        method, path, body = self.calls[-1]
        self.assertEqual(method, 'PATCH')
        self.assertFalse(body['force'])
        commit = next(b for m, p, b in self.calls if m == 'POST' and p == '/git/commits')
        self.assertEqual(commit['parents'], [self.existing])


if __name__ == '__main__':
    unittest.main()
