package api

import (
	"encoding/json"
	"github.com/eyupio/zoomies/internal/aicontext"
	"github.com/eyupio/zoomies/internal/auth"
	"github.com/eyupio/zoomies/internal/controller"
	"github.com/eyupio/zoomies/internal/cryptox"
	"github.com/eyupio/zoomies/internal/github"
	"github.com/eyupio/zoomies/internal/mcp"
	"github.com/eyupio/zoomies/internal/store"
	"net/http"
	"strings"
	"testing"
	"time"
)

func sourceHarness(t *testing.T) (*harness, store.AIContextRepository, *store.User, string) {
	t.Helper()
	h, inst, _ := migrationHarness(t)
	reader, admin := h.user("ingestion-admin", store.RoleAdmin)
	discovery, err := h.ctrl.DiscoverAIContext(h.ctx, inst.ID)
	if err != nil {
		t.Fatal(err)
	}
	selected := discovery.Repositories[0]
	draft := store.AIContextRepository{Key: aicontext.RepositoryKey{GitHubHost: "github.com", InstallationID: inst.ID, RepositoryID: selected.ID}, FullName: selected.FullName, Config: aicontext.DefaultConfig(selected.DefaultBranch)}
	if err := h.st.CreateAIContextRepository(h.ctx, &draft); err != nil {
		t.Fatal(err)
	}
	if err := h.st.ReplaceAIContextMembers(h.ctx, draft.ID, []string{reader.ID}); err != nil {
		t.Fatal(err)
	}
	plan, err := h.ctrl.PreviewAIContextSetup(h.ctx, draft.ID)
	if err != nil {
		t.Fatal(err)
	}
	plan, err = h.ctrl.CreateAIContextSetupPR(h.ctx, draft.ID, controller.AIContextSetupApproval{Revision: plan.Revision, PlanHash: plan.PlanHash})
	if err != nil {
		t.Fatal(err)
	}

	if !h.gh.MergeContextPull(draft.FullName, plan.Setup.PRNumber) {
		t.Fatal("merge failed")
	}
	client, err := h.ctrl.ClientFor(h.ctx, inst.ID)
	if err != nil {
		t.Fatal(err)
	}
	h.gh.AddFile(draft.FullName, "src/main.go", "package widgets\n")
	h.gh.AddFile(draft.FullName, "src/helper.go", "package widgets\n// helper\n")
	source, err := client.(github.ContextSetupClient).ReadContextSetup(h.ctx, draft.FullName, draft.Config.SourceBranch)
	if err != nil {
		t.Fatal(err)
	}
	hash, _ := draft.Config.Hash()
	snapshot := aicontext.Snapshot{Manifest: aicontext.Manifest{SchemaVersion: 1, Repository: draft.Key, SourceBranch: draft.Config.SourceBranch, SourceCommit: source.Commit, ConfigHash: hash, GeneratedAt: time.Now().UTC(), Manager: "zoomies", Generator: "repomix@1.18.1"}, Files: []aicontext.File{{Path: "src/main.go", Content: "package widgets\n", SHA256: aicontext.Hash([]byte("package widgets\n"))}, {Path: "src/helper.go", Content: "package widgets\n// helper\n", SHA256: aicontext.Hash([]byte("package widgets\n// helper\n"))}}}
	body, _ := json.Marshal(snapshot)
	manifest, _ := json.Marshal(map[string]string{"snapshot_sha256": aicontext.Hash(body)})
	h.gh.SetContextBranch(draft.FullName, aicontext.OutputBranch, map[string]string{aicontext.OutputDirectory + "/snapshot.json": string(body), aicontext.OutputDirectory + "/manifest.json": string(manifest), aicontext.OutputDirectory + "/NOTICE.md": "Managed by Zoomies AI Context. Generated by Repomix. Do not edit.\n"})
	if err := h.ctrl.RefreshAIContext(h.ctx, draft.ID); err != nil {
		t.Fatal(err)
	}

	return h, draft, reader, admin
}

func TestContextSourceRetrievalRequiresExplicitMembershipAndPinsPages(t *testing.T) {
	h, draft, owner, cookie := sourceHarness(t)
	_, other := h.user("source-outsider", store.RoleAdmin)
	base := "/api/v1/ai-context/source/" + draft.ID + "/"
	before := len(h.gh.Requests())
	h.do(request{method: http.MethodGet, path: base + "read?path=src/main.go", cookie: other}).mustStatus(t, http.StatusNotFound, "non-member admin")
	if len(h.gh.Requests()) != before {
		t.Fatal("unauthorised retrieval contacted GitHub")
	}
	for _, op := range []string{"overview?limit=1", "read?path=src/main.go", "search?query=widgets", "pack?path=src/main.go&path=src/helper.go"} {
		r := h.do(request{method: http.MethodGet, path: base + op, cookie: cookie})
		r.mustStatus(t, http.StatusOK, op)
		if r.header.Get("Cache-Control") != "no-store" || len(r.body) > 8000 {
			t.Fatal("source cache or budget")
		}
		var page aicontext.Page
		r.into(t, &page)
		if len(page.Commit) != 40 || page.Snapshot == "" {
			t.Fatal("source identity missing")
		}
	}
	h.do(request{method: http.MethodGet, path: base + "read?path=src/main.go&offset=1", cookie: cookie}).mustStatus(t, http.StatusUnprocessableEntity, "unpinned continuation")
	h.do(request{method: http.MethodGet, path: base + "read?path=src/main.go&commit=" + strings.Repeat("a", 40), cookie: cookie}).mustStatus(t, http.StatusConflict, "different source commit")
	tokenRow, token, err := h.ctrl.Auth().CreateAPIToken(h.ctx, auth.NewToken{Name: "source-reader", Role: store.RoleViewer, UserID: owner.ID, Scopes: []string{"context:read"}})
	if err != nil {
		t.Fatal(err)
	}
	result := h.mcpTool(token, "context_read", map[string]any{"repository_id": draft.ID, "path": "src/main.go"})
	if result.IsError || !strings.Contains(resultText(result), "package widgets") {
		t.Fatal("MCP source read", result)
	}
	if err := h.st.RevokeAPIToken(h.ctx, tokenRow.ID); err != nil {
		t.Fatal(err)
	}
	h.do(request{method: http.MethodGet, path: base + "read?path=src/main.go", token: token}).mustStatus(t, http.StatusUnauthorized, "revoked token")
	h.gh.SetPermissions(map[string]string{"metadata": "read"})
	r := h.do(request{method: http.MethodGet, path: base + "read?path=src/main.go", cookie: cookie})
	if r.status == http.StatusOK || strings.Contains(string(r.body), "package widgets") {
		t.Fatal("revoked GitHub access leaked retained source")
	}
}

func TestContextMCPDiscoveryAndReadsFollowTheConnectionsExplicitConsent(t *testing.T) {
	h, draft, owner, cookie := sourceHarness(t)
	h.cfg.Server.ExternalURL = oauthBase
	client := h.registerClient(claudeReturn)
	req := requestFrom(t, h.authorize(client, claudeReturn, nil))
	pair := pairFrom(t, h.exchange(client, h.approve(cookie, req, store.RoleViewer), nil, nil))
	args := map[string]any{"repository_id": draft.ID, "path": "src/main.go"}
	if result := h.mcpTool(pair.AccessToken, "context_read", args); !result.IsError {
		t.Fatal("old fleet approval gained source")
	}
	discovery := h.mcpTool(pair.AccessToken, "context_overview", map[string]any{})
	if discovery.IsError || strings.Contains(resultText(discovery), draft.FullName) {
		t.Fatal("unconsented repository discovery", discovery)
	}
	grants, err := h.st.ListOAuthGrants(h.ctx, owner.ID)
	if err != nil || len(grants) != 1 {
		t.Fatal("grant", err)
	}
	if err := h.st.ReplaceAIContextConnectionAccess(h.ctx, grants[0].ID, owner.ID, []string{draft.ID}); err != nil {
		t.Fatal(err)
	}
	for _, op := range []string{"context_read", "context_pack", "context_search", "context_overview"} {
		a := map[string]any{"repository_id": draft.ID}
		if op == "context_read" {
			a["path"] = "src/main.go"
		}
		if op == "context_pack" {
			a["paths"] = []string{"src/main.go", "src/helper.go"}
		}
		if op == "context_search" {
			a["query"] = "widgets"
		}
		result := h.mcpTool(pair.AccessToken, op, a)
		if result.IsError {
			t.Fatal(op, result)
		}
		b, _ := json.Marshal(result)
		if len(b) > 32000 {
			t.Fatal("MCP encoded bound")
		}
	}
	discovery = h.mcpTool(pair.AccessToken, "context_overview", map[string]any{})
	if discovery.IsError || !strings.Contains(resultText(discovery), draft.FullName) {
		t.Fatal("consented discovery missing", discovery)
	}
	if err := h.st.ReplaceAIContextMembers(h.ctx, draft.ID, nil); err != nil {
		t.Fatal(err)
	}
	if result := h.mcpTool(pair.AccessToken, "context_read", args); !result.IsError {
		t.Fatal("removed membership remained readable")
	}
	if err := h.st.ReplaceAIContextMembers(h.ctx, draft.ID, []string{owner.ID}); err != nil {
		t.Fatal(err)
	}
	if result := h.mcpTool(pair.AccessToken, "context_read", args); !result.IsError {
		t.Fatal("re-add restored old connection consent")
	}
	// Removing just the access token leaves the grant and consent intact. This
	// specifically exercises credential revalidation, beyond membership checks.
	if err := h.st.ReplaceAIContextConnectionAccess(h.ctx, grants[0].ID, owner.ID, []string{draft.ID}); err != nil {
		t.Fatal(err)
	}
	h.gh.SetDelay("GET", "/app", 150*time.Millisecond)
	before := len(h.gh.Requests())
	done := make(chan mcp.CallResult, 1)
	go func() { done <- h.mcpTool(pair.AccessToken, "context_read", args) }()
	waitForContextVerification(t, h, before)
	if err := h.st.DeleteOAuthToken(h.ctx, cryptox.HashToken(pair.AccessToken)); err != nil {
		t.Fatal(err)
	}
	if result := <-done; !result.IsError || strings.Contains(resultText(result), "package widgets") {
		t.Fatal("revoked in-flight OAuth token leaked source")
	}
	// The OAuth token remains accepted exclusively on /mcp.
	h.do(request{method: http.MethodGet, path: "/api/v1/ai-context/source/" + draft.ID + "/read?path=src/main.go", token: pair.AccessToken}).mustStatus(t, http.StatusUnauthorized, "OAuth token on REST")
}

func TestContextSourceRevocationDuringLiveVerificationClosesTheReply(t *testing.T) {
	h, draft, _, cookie := sourceHarness(t)
	h.gh.SetDelay("GET", "/app", 150*time.Millisecond)
	before := len(h.gh.Requests())
	done := make(chan *response, 1)
	go func() {
		done <- h.do(request{method: http.MethodGet, path: "/api/v1/ai-context/source/" + draft.ID + "/read?path=src/main.go", cookie: cookie})
	}()
	waitForContextVerification(t, h, before)
	if err := h.st.ReplaceAIContextMembers(h.ctx, draft.ID, nil); err != nil {
		t.Fatal(err)
	}
	response := <-done
	if response.status == http.StatusOK || strings.Contains(string(response.body), "package widgets") {
		t.Fatal("in-flight revocation leaked source")
	}
}

func waitForContextVerification(t *testing.T, h *harness, before int) {
	t.Helper()
	deadline := time.NewTimer(3 * time.Second)
	defer deadline.Stop()
	tick := time.NewTicker(time.Millisecond)
	defer tick.Stop()
	for len(h.gh.Requests()) <= before {
		select {
		case <-deadline.C:
			t.Fatal("verification never started")
		case <-tick.C:
		}
	}
}
