package api

import (
	"encoding/json"
	"net/http"
	"strings"
	"testing"
	"time"

	"github.com/eyupio/zoomies/internal/aicontext"
	"github.com/eyupio/zoomies/internal/controller"
	"github.com/eyupio/zoomies/internal/github"
	"github.com/eyupio/zoomies/internal/store"
)

func TestContextIngestionRequiresMergeAndClosesAccessOnDriftOrRevocation(t *testing.T) {
	h, inst, _ := migrationHarness(t)
	reader, admin := h.user("ingestion-admin", store.RoleAdmin)
	discovery, err := h.ctrl.DiscoverAIContext(h.ctx, inst.ID)
	if err != nil {
		t.Fatal(err)
	}
	selected := discovery.Repositories[0]
	draft := store.AIContextRepository{Key: aicontext.RepositoryKey{GitHubHost: "github.com", InstallationID: inst.ID, RepositoryID: selected.ID}, FullName: selected.FullName, Config: aicontext.DefaultConfig(selected.DefaultBranch)}
	if err := h.st.CreateAIContextRepository(h.ctx, &draft); err != nil {
		t.Fatal(err)
	}
	if err := h.st.ReplaceAIContextMembers(h.ctx, draft.ID, []string{reader.ID}); err != nil {
		t.Fatal(err)
	}
	plan, err := h.ctrl.PreviewAIContextSetup(h.ctx, draft.ID)
	if err != nil {
		t.Fatal(err)
	}
	plan, err = h.ctrl.CreateAIContextSetupPR(h.ctx, draft.ID, controller.AIContextSetupApproval{Revision: plan.Revision, PlanHash: plan.PlanHash})
	if err != nil {
		t.Fatal(err)
	}
	if err := h.ctrl.RefreshAIContext(h.ctx, draft.ID); err == nil {
		t.Fatal("unmerged setup activated")
	}
	unmerged, err := h.st.GetAIContextFreshness(h.ctx, draft.ID)
	if err != nil || unmerged.State != "awaiting_merge" {
		t.Fatalf("unmerged state: %+v %v", unmerged, err)
	}
	if !h.gh.MergeContextPull(draft.FullName, plan.Setup.PRNumber) {
		t.Fatal("merge failed")
	}
	client, err := h.ctrl.ClientFor(h.ctx, inst.ID)
	if err != nil {
		t.Fatal(err)
	}
	h.gh.AddFile(draft.FullName, "src/main.go", "package widgets\n")
	source, err := client.(github.ContextSetupClient).ReadContextSetup(h.ctx, draft.FullName, draft.Config.SourceBranch)
	if err != nil {
		t.Fatal(err)
	}
	hash, _ := draft.Config.Hash()
	snapshot := aicontext.Snapshot{Manifest: aicontext.Manifest{SchemaVersion: 1, Repository: draft.Key, SourceBranch: draft.Config.SourceBranch, SourceCommit: source.Commit, ConfigHash: hash, GeneratedAt: time.Now().UTC(), Manager: "zoomies", Generator: "repomix@1.18.1"}, Files: []aicontext.File{{Path: "src/main.go", Content: "package widgets\n", SHA256: aicontext.Hash([]byte("package widgets\n"))}}}
	body, _ := json.Marshal(snapshot)
	manifest, _ := json.Marshal(map[string]string{"snapshot_sha256": aicontext.Hash(body)})
	h.gh.SetContextBranch(draft.FullName, aicontext.OutputBranch, map[string]string{aicontext.OutputDirectory + "/snapshot.json": string(body), aicontext.OutputDirectory + "/manifest.json": string(manifest), aicontext.OutputDirectory + "/NOTICE.md": "Managed by Zoomies AI Context. Generated by Repomix. Do not edit.\n"})
	if err := h.ctrl.RefreshAIContext(h.ctx, draft.ID); err != nil {
		t.Fatal(err)
	}
	check := func(want bool) {
		t.Helper()
		allowed, err := h.st.AIContextUserAccess(h.ctx, draft.ID, reader.ID)
		if err != nil || allowed != want {
			t.Fatalf("source access: %v %v", allowed, err)
		}
	}
	check(true)
	response := h.do(request{method: http.MethodPost, path: "/api/v1/ai-context/repositories/" + draft.ID + "/recheck", cookie: admin})
	response.mustStatus(t, http.StatusOK, "freshness")
	var saved store.AIContextRepository
	response.into(t, &saved)
	if saved.Freshness == nil || saved.Freshness.State != "ready" || saved.Freshness.Digest == "" {
		t.Fatalf("freshness absent: %+v", saved)
	}
	digest := saved.Freshness.Digest
	if _, _, err := h.ctrl.VerifiedAIContextSnapshot(h.ctx, draft.ID); err != nil {
		t.Fatal("cached verification", err)
	}
	h.gh.SetPermissions(map[string]string{"metadata": "read"})
	if _, _, err := h.ctrl.VerifiedAIContextSnapshot(h.ctx, draft.ID); err == nil {
		t.Fatal("revoked GitHub contents still readable")
	}
	check(false)
	h.gh.SetPermissions(map[string]string{"metadata": "read", "contents": "write", "workflows": "write"})
	if err := h.ctrl.RefreshAIContext(h.ctx, draft.ID); err != nil {
		t.Fatal("recovery", err)
	}
	check(true)
	h.gh.AddFile(draft.FullName, aicontext.WorkflowPath, "unreviewed workflow")
	if err := h.ctrl.RefreshAIContext(h.ctx, draft.ID); err == nil {
		t.Fatal("workflow drift admitted")
	}
	check(false)
	// The card says what to do about it, not merely that verification failed.
	if drift, err := h.st.GetAIContextFreshness(h.ctx, draft.ID); err != nil || !strings.Contains(drift.Failure, "edited after review") {
		t.Fatalf("drift reason: %+v %v", drift, err)
	}
	h.gh.AddFile(draft.FullName, aicontext.WorkflowPath, findSetupContent(t, plan, aicontext.WorkflowPath))
	h.gh.AddFile(draft.FullName, "src/main.go", "package newer\n")
	if err := h.ctrl.RefreshAIContext(h.ctx, draft.ID); err == nil {
		t.Fatal("stale source admitted")
	}
	check(false)
	fresh, err := h.st.GetAIContextFreshness(h.ctx, draft.ID)
	if err != nil || fresh.State != "stale" || fresh.Digest != digest || fresh.DesiredCommit == snapshot.Manifest.SourceCommit {
		t.Fatalf("stale status: %+v %v", fresh, err)
	}
	// A branch that moved on is the ordinary stale case, and is named as such.
	if !strings.Contains(fresh.Failure, "older commit") || !strings.Contains(fresh.Failure, "Regenerate") {
		t.Fatalf("stale reason does not say the branch moved on: %q", fresh.Failure)
	}
	if _, err := h.st.GetAIContextSnapshot(h.ctx, draft.ID, digest); err != nil {
		t.Fatal("failure deleted the last valid snapshot", err)
	}
	// API metadata never includes source or generator diagnostics.
	response = h.do(request{method: http.MethodGet, path: "/api/v1/ai-context/repositories/" + draft.ID, cookie: admin})
	response.into(t, &saved)
	if strings.Contains(saved.Freshness.Failure, "package") {
		t.Fatal("failure exposed source")
	}
}

func findSetupContent(t *testing.T, plan *controller.AIContextSetupPreview, path string) string {
	t.Helper()
	for _, file := range plan.Files {
		if file.Path == path {
			return file.Content
		}
	}
	t.Fatal("missing setup file", path)
	return ""
}

func TestRegeneratingContextRunsTheReviewedWorkflowOnly(t *testing.T) {
	h, inst, _ := migrationHarness(t)
	_, admin := h.user("regenerate-admin", store.RoleAdmin)
	discovery, err := h.ctrl.DiscoverAIContext(h.ctx, inst.ID)
	if err != nil {
		t.Fatal(err)
	}
	selected := discovery.Repositories[0]
	draft := store.AIContextRepository{Key: aicontext.RepositoryKey{GitHubHost: "github.com", InstallationID: inst.ID, RepositoryID: selected.ID}, FullName: selected.FullName, Config: aicontext.DefaultConfig(selected.DefaultBranch)}
	if err := h.st.CreateAIContextRepository(h.ctx, &draft); err != nil {
		t.Fatal(err)
	}
	plan, err := h.ctrl.PreviewAIContextSetup(h.ctx, draft.ID)
	if err != nil {
		t.Fatal(err)
	}
	plan, err = h.ctrl.CreateAIContextSetupPR(h.ctx, draft.ID, controller.AIContextSetupApproval{Revision: plan.Revision, PlanHash: plan.PlanHash})
	if err != nil {
		t.Fatal(err)
	}
	path := "/api/v1/ai-context/repositories/" + draft.ID + "/regenerate"

	// Nothing is reviewed until the setup PR is merged, so there is no workflow
	// to trust and nothing to run.
	h.do(request{method: http.MethodPost, path: path, cookie: admin}).mustStatus(t, http.StatusConflict, "regenerating before the setup is merged")
	if n := h.gh.ContextDispatches(draft.FullName); n != 0 {
		t.Fatalf("workflow dispatched before the setup was reviewed: %d", n)
	}

	if !h.gh.MergeContextPull(draft.FullName, plan.Setup.PRNumber) {
		t.Fatal("merge failed")
	}
	response := h.do(request{method: http.MethodPost, path: path, cookie: admin})
	response.mustStatus(t, http.StatusAccepted, "regenerating a merged setup")
	if n := h.gh.ContextDispatches(draft.FullName); n != 1 {
		t.Fatalf("dispatches: %d", n)
	}

	// An edited workflow is not what was reviewed; running it would run
	// whatever it now says.
	h.gh.AddFile(draft.FullName, aicontext.WorkflowPath, "unreviewed workflow")
	h.do(request{method: http.MethodPost, path: path, cookie: admin}).mustStatus(t, http.StatusConflict, "regenerating an edited workflow")
	h.gh.AddFile(draft.FullName, aicontext.WorkflowPath, findSetupContent(t, plan, aicontext.WorkflowPath))
	if n := h.gh.ContextDispatches(draft.FullName); n != 1 {
		t.Fatalf("an edited workflow was dispatched: %d", n)
	}

	// Without Actions write the request is refused with the permission to grant.
	h.gh.SetPermissions(map[string]string{"metadata": "read", "contents": "write", "workflows": "write", "actions": "read"})
	denied := h.do(request{method: http.MethodPost, path: path, cookie: admin})
	denied.mustStatus(t, http.StatusConflict, "regenerating without Actions write")
	if !strings.Contains(denied.errorMessage(t), "Actions") {
		t.Fatalf("refusal does not name the permission: %s", denied.errorMessage(t))
	}

	// Nothing has been generated yet, and the card says to run the workflow
	// rather than "could not be verified".
	h.gh.SetPermissions(map[string]string{"metadata": "read", "contents": "write", "workflows": "write", "actions": "write"})
	if err := h.ctrl.RefreshAIContext(h.ctx, draft.ID); err == nil {
		t.Fatal("context admitted with nothing generated")
	}
	fresh, err := h.st.GetAIContextFreshness(h.ctx, draft.ID)
	if err != nil || fresh.State != "stale" || !strings.Contains(fresh.Failure, "Regenerate") {
		t.Fatalf("freshness: %+v %v", fresh, err)
	}
}

func TestSyncingContextStartsTheWorkflowOnlyWhenItIsBehindAndAfterTheGrace(t *testing.T) {
	h, inst, _ := migrationHarness(t)
	discovery, err := h.ctrl.DiscoverAIContext(h.ctx, inst.ID)
	if err != nil {
		t.Fatal(err)
	}
	selected := discovery.Repositories[0]
	draft := store.AIContextRepository{Key: aicontext.RepositoryKey{GitHubHost: "github.com", InstallationID: inst.ID, RepositoryID: selected.ID}, FullName: selected.FullName, Config: aicontext.DefaultConfig(selected.DefaultBranch)}
	if err := h.st.CreateAIContextRepository(h.ctx, &draft); err != nil {
		t.Fatal(err)
	}
	plan, err := h.ctrl.PreviewAIContextSetup(h.ctx, draft.ID)
	if err != nil {
		t.Fatal(err)
	}
	plan, err = h.ctrl.CreateAIContextSetupPR(h.ctx, draft.ID, controller.AIContextSetupApproval{Revision: plan.Revision, PlanHash: plan.PlanHash})
	if err != nil {
		t.Fatal(err)
	}
	dispatches := func() int { return h.gh.ContextDispatches(draft.FullName) }

	// Until the setup is reviewed there is nothing to run.
	_ = h.ctrl.SyncAIContext(h.ctx, draft.ID, 0)
	if dispatches() != 0 {
		t.Fatalf("workflow started before the setup was merged: %d", dispatches())
	}

	if !h.gh.MergeContextPull(draft.FullName, plan.Setup.PRNumber) {
		t.Fatal("merge failed")
	}
	// The push-triggered run gets its grace before the controller steps in.
	_ = h.ctrl.SyncAIContext(h.ctx, draft.ID, time.Hour)
	if dispatches() != 0 {
		t.Fatalf("workflow started inside the grace period: %d", dispatches())
	}

	// Past the grace, a repository with nothing published for the current
	// commit gets one run, and a second pass does not pile another on top.
	_ = h.ctrl.SyncAIContext(h.ctx, draft.ID, 0)
	_ = h.ctrl.SyncAIContext(h.ctx, draft.ID, 0)
	if dispatches() != 1 {
		t.Fatalf("dispatches: %d, want 1", dispatches())
	}

	// A failure a run cannot fix is left alone: an edited workflow would only
	// fail again, and must not be started.
	h.gh.AddFile(draft.FullName, aicontext.WorkflowPath, "unreviewed workflow")
	_ = h.ctrl.SyncAIContext(h.ctx, draft.ID, 0)
	if dispatches() != 1 {
		t.Fatalf("workflow started after the setup drifted: %d", dispatches())
	}
}
