//go:build ignore

// Command gen_openapi copies api/openapi.yaml into this package as Go source.
//
// The API has to be able to serve the contract it implements, and go:embed
// cannot reach outside its own package directory -- api/openapi.yaml lives at
// the top of the repository, deliberately, because it is the document the UI's
// TypeScript client is generated from as well. Copying the file into
// internal/api would leave two files that could disagree, so the copy is
// generated, compressed, and checked against the original by a test that fails
// with the command to run.
//
// Run it from the repository root after editing the spec:
//
//	go run internal/api/gen_openapi.go
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"os"
	"strings"
)

const (
	defaultSource = "api/openapi.yaml"
	target        = "internal/api/openapi_spec.go"
	// lineWidth keeps the generated literal reviewable in a diff.
	lineWidth = 96
)

func main() {
	source := defaultSource
	if len(os.Args) > 1 {
		source = os.Args[1]
	}
	raw, err := os.ReadFile(source)
	if err != nil {
		fail("reading %s: %v", source, err)
	}

	var buf bytes.Buffer
	zw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		fail("compressing: %v", err)
	}
	if _, err := zw.Write(raw); err != nil {
		fail("compressing: %v", err)
	}
	if err := zw.Close(); err != nil {
		fail("compressing: %v", err)
	}

	encoded := base64.StdEncoding.EncodeToString(buf.Bytes())

	var out strings.Builder
	out.WriteString("// Code generated by gen_openapi.go; DO NOT EDIT.\n")
	out.WriteString("// Source: " + defaultSource + "\n\n")
	out.WriteString("package api\n\n")
	out.WriteString("// openapiSpecGzB64 is api/openapi.yaml, gzipped and base64 encoded.\n")
	out.WriteString("//\n")
	out.WriteString("// It is generated rather than embedded because go:embed cannot reach a file\n")
	out.WriteString("// outside its package directory. openapi_spec_test.go compares it with the\n")
	out.WriteString("// original on every test run, so the two cannot drift apart unnoticed; when it\n")
	out.WriteString("// fails, run `go run internal/api/gen_openapi.go` from the repository root.\n")
	out.WriteString("const openapiSpecGzB64 = \"\" +\n")
	for i := 0; i < len(encoded); i += lineWidth {
		end := min(i+lineWidth, len(encoded))
		out.WriteString("\t\"" + encoded[i:end] + "\"")
		if end < len(encoded) {
			out.WriteString(" +")
		}
		out.WriteString("\n")
	}

	if err := os.WriteFile(target, []byte(out.String()), 0o644); err != nil {
		fail("writing %s: %v", target, err)
	}
	fmt.Printf("wrote %s (%d bytes of YAML, %d bytes encoded)\n", target, len(raw), len(encoded))
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_openapi: "+format+"\n", args...)
	os.Exit(1)
}
