package main

import (
	"bytes"
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"syscall"
	"time"

	"github.com/eyupio/zoomies/internal/gateway"
	"github.com/eyupio/zoomies/internal/proxmoxsetup"
	"github.com/tailscale/tailcat"
)

func providersConnectProxmox(ctx context.Context, e *env, args []string) error {
	fs := newFlagSet(e, "zoomies providers connect-proxmox --controller <url> --setup-id <id> --token <token>", "Connect this Proxmox host using the command generated by the provider wizard.")
	controller := fs.String("controller", "", "private or HTTPS controller address from the wizard")
	id := fs.String("setup-id", "", "the short-lived provider setup ID")
	token := fs.String("token", "", "the single-use provider setup token")
	if err := fs.parse(args); err != nil {
		return err
	}
	if err := fs.noMoreArgs(); err != nil {
		return err
	}
	u, err := url.Parse(*controller)
	if err != nil || (u.Scheme != "https" && u.Scheme != "tailcat") || u.Hostname() == "" || u.User != nil || u.RawQuery != "" || u.Fragment != "" || *id == "" || *token == "" {
		return usagef(fs.Name(), "use the complete setup command generated by the provider wizard")
	}
	if runtime.GOOS != "linux" || os.Geteuid() != 0 {
		return errors.New("Run this command as root on a Linux Proxmox host.")
	}
	for _, name := range []string{"pveum", "systemctl"} {
		if _, err := exec.LookPath(name); err != nil {
			return fmt.Errorf("This Proxmox host needs %s to connect.", name)
		}
	}
	if u.Scheme == "tailcat" {
		if _, err := tailcat.ParseAddr(tailcat.Addr(strings.TrimPrefix(*controller, "tailcat://"))); err != nil {
			return errors.New("Invalid private controller address; copy the complete command from the wizard.")
		}
	}
	*controller = strings.TrimRight(*controller, "/")
	key := proxmoxsetup.InstanceKey(*controller)
	dir := filepath.Join("/var/lib/zoomies-proxmox", key)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}
	if err := os.Chmod(dir, 0700); err != nil {
		return err
	}
	run := func(ctx context.Context, name string, args ...string) ([]byte, error) {
		// pveum's output contains the new token. Never echo command output on failure.
		return exec.CommandContext(ctx, name, args...).Output()
	}
	// flock is released by the kernel even if setup is interrupted.
	lock, err := os.OpenFile(filepath.Join(dir, "setup.lock"), os.O_CREATE|os.O_RDWR, 0600)
	if err != nil {
		return err
	}
	defer lock.Close()
	if err := syscall.Flock(int(lock.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		return errors.New("Another setup is running for this controller; retry when it finishes.")
	}
	defer syscall.Flock(int(lock.Fd()), syscall.LOCK_UN)
	receipt := filepath.Join(dir, "completed-"+proxmoxsetup.InstanceKey(*id+*token))
	// Completion survives provider creation and setup-token expiry.
	if _, err := os.Stat(receipt); err == nil {
		if _, err := run(ctx, "systemctl", "start", "zoomies-proxmox-"+key+".service"); err != nil {
			return err
		}
		fmt.Fprintln(e.out, "Proxmox is already connected; its saved connection has been preserved.")
		return nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	atomicWrite := func(path string, data []byte, mode os.FileMode) error {
		if err := os.WriteFile(path+".new", data, mode); err != nil {
			return err
		}
		return os.Rename(path+".new", path)
	}
	h := proxmoxsetup.Host{ReadFile: os.ReadFile, WriteFile: atomicWrite, Run: run}
	fmt.Fprintln(e.out, "Preparing this Proxmox host's private provider connection...")
	conn, err := proxmoxsetup.Prepare(ctx, h, dir, key)
	if err != nil {
		return err
	}
	tokenID, _, ok := strings.Cut(conn.Credential, "=")
	if !ok {
		return errors.New("The saved Proxmox API credential is incomplete; restore it before retrying.")
	}
	// Reconcile the dedicated role when a newer release needs permissions.
	if _, err := run(ctx, "pveum", "role", "modify", "Zoomies-"+key, "--privs", proxmoxsetup.ProviderPrivileges); err != nil {
		return errors.New("Cannot update the dedicated Proxmox role; check permissions and retry.")
	}
	if err := proxmoxsetup.GrantToken(ctx, h, tokenID, "Zoomies-"+key); err != nil {
		return err
	}
	// Confirm the local API using the same certificate and name the controller
	// will verify through the gateway; no verification bypass is needed.
	endpoint, _ := url.Parse(conn.Endpoint)
	roots := x509.NewCertPool()
	roots.AppendCertsFromPEM([]byte(conn.CAPEM))
	dialer := &tls.Dialer{NetDialer: &net.Dialer{Timeout: 10 * time.Second}, Config: &tls.Config{RootCAs: roots, ServerName: endpoint.Hostname(), MinVersion: tls.VersionTLS12}}
	local, err := dialer.DialContext(ctx, "tcp", "127.0.0.1:8006")
	if err != nil {
		return errors.New("Cannot verify the local Proxmox API certificate. Check pveproxy and its certificate before retrying.")
	}
	local.Close()
	unitName := "zoomies-proxmox-" + key + ".service"
	// A live gateway already has an identity; do not start a second Tailcat
	// listener with that key just to read its address on a repeated setup.
	raw, err := os.ReadFile(gateway.StatePath(dir))
	if errors.Is(err, os.ErrNotExist) {
		g, err := gateway.Start(ctx, gateway.Options{Target: "127.0.0.1:8006", StateDir: dir})
		if err != nil {
			return err
		}
		conn.TailcatAddress = g.Address()
		if err := g.Close(); err != nil {
			return err
		}
	} else if err != nil {
		return err
	} else {
		var identity tailcat.PrivateKey
		if json.Unmarshal(raw, &identity) != nil || identity.Private.IsZero() || identity.Public.PresharedKey.IsZero() {
			return errors.New("The saved provider gateway identity is incomplete; restore it before retrying.")
		}
		conn.TailcatAddress = string(identity.Public.Addr())
	}
	if err := conn.Validate(); err != nil {
		return err
	}
	source, err := os.Executable()
	if err != nil {
		return err
	}
	binary, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	binaryPath := filepath.Join(dir, "zoomies")
	// Rename atomically: a running gateway continues with its current inode.
	if err := os.WriteFile(binaryPath+".new", binary, 0700); err != nil {
		return err
	}
	if err := os.Rename(binaryPath+".new", binaryPath); err != nil {
		return err
	}
	unit := "[Unit]\nDescription=Zoomies Proxmox private API connection\nWants=network-online.target\nAfter=network-online.target\n\n[Service]\nType=simple\nExecStart=" + binaryPath + " gateway --target 127.0.0.1:8006 --state-dir " + dir + " --quiet\nRestart=on-failure\nRestartSec=5\nUMask=0077\n\n[Install]\nWantedBy=multi-user.target\n"
	if err := os.WriteFile(filepath.Join("/etc/systemd/system", unitName), []byte(unit), 0644); err != nil {
		return err
	}
	for _, argv := range [][]string{{"daemon-reload"}, {"enable", unitName}, {"restart", unitName}, {"is-active", "--quiet", unitName}} {
		if _, err := run(ctx, "systemctl", argv...); err != nil {
			return fmt.Errorf("Cannot start the private provider connection; check systemctl status %s and retry.", unitName)
		}
	}
	payload, err := json.Marshal(conn)
	if err != nil {
		return err
	}
	callbackURL := *controller
	client := &http.Client{Timeout: 30 * time.Second, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	if u.Scheme == "tailcat" {
		address := strings.TrimPrefix(*controller, "tailcat://")
		if _, err := tailcat.ParseAddr(tailcat.Addr(address)); err != nil {
			return errors.New("Invalid private controller address; copy the whole command from the wizard.")
		}
		tunnel := tailcat.NewClient(tailcat.Addr(address))
		tunnel.Logf = func(string, ...any) {}
		defer tunnel.Close()
		transport := &http.Transport{DisableKeepAlives: true, DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
			if _, err := tunnel.Ping(ctx); err != nil {
				return nil, err
			}
			return tunnel.DialTCPPort(ctx, 80)
		}}
		defer transport.CloseIdleConnections()
		client.Transport = transport
		callbackURL = "http://127.0.0.1"
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, callbackURL+"/api/v1/provider-setups/"+url.PathEscape(*id)+"/complete", bytes.NewReader(payload))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+*token)
	req.Header.Set("Content-Type", "application/json")
	// A redirect must never forward either the setup capability or API token.
	resp, err := client.Do(req)
	if err != nil {
		return errors.New("The controller could not be reached securely. Check its HTTPS address and rerun the setup command; the saved Proxmox credential and gateway will be reused.")
	}
	defer resp.Body.Close()
	_, _ = io.Copy(io.Discard, io.LimitReader(resp.Body, 4096))
	if resp.StatusCode != http.StatusNoContent {
		return fmt.Errorf("The controller refused this setup (HTTP %d). Generate a new command in the wizard and rerun it; the existing provider connection will be reused.", resp.StatusCode)
	}
	if err := atomicWrite(receipt, []byte("connected\n"), 0600); err != nil {
		return err
	}
	fmt.Fprintln(e.out, "Proxmox connected. Return to Zoomies to choose the VM template and capacity.")
	return nil
}
