//go:build ignore

// Command gen_lock resolves every image reference this deployment package
// depends on to the digest it points at today, and writes images.lock.
//
// A marketplace artefact promises a particular build, and a tag cannot keep
// that promise: tags move, and the person deploying six months from now has no
// way to tell that the controller they got is not the one that was tested. The
// lock file is the record that makes the promise checkable -- it is what an
// operator, an auditor or a provider's security review compares a running
// deployment against.
//
// The catalogue in internal/naming is the source for which runner variants
// exist, so a new operating system is picked up here by adding its row there
// rather than by remembering this file.
//
// Run it from the repository root after changing the release in release.env:
//
//	make marketplace-lock
//
// It needs network access to the registry and nothing else: the manifests it
// asks for are public, and it pulls no layers.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/eyupio/zoomies/internal/naming"
)

const (
	dir      = "deploy/marketplace"
	lockFile = "images.lock"
	envFile  = "release.env"
)

// manifestTypes is every media type the registry may answer a manifest request
// with. A multi-architecture image is an index, a single-architecture one is a
// manifest, and both spellings of each are still in the wild; asking for only
// one of them gets a 404 that looks like a missing tag.
const manifestTypes = "application/vnd.oci.image.index.v1+json, " +
	"application/vnd.docker.distribution.manifest.list.v2+json, " +
	"application/vnd.oci.image.manifest.v1+json, " +
	"application/vnd.docker.distribution.manifest.v2+json"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen_lock:", err)
		os.Exit(1)
	}
}

func run() error {
	env, err := readEnv(filepath.Join(dir, envFile))
	if err != nil {
		return err
	}
	release := env["ZOOMIES_RELEASE"]
	if release == "" {
		return fmt.Errorf("%s names no ZOOMIES_RELEASE", envFile)
	}

	refs := []string{stripDigest(env["ZOOMIES_CONTROLLER_IMAGE"])}
	if proxy := stripDigest(env["ZOOMIES_PROXY_IMAGE"]); proxy != "" {
		refs = append(refs, proxy)
	}
	for _, img := range naming.Images() {
		tag := img.Tag() + "-" + release
		refs = append(refs,
			env["ZOOMIES_RUNNER_REPO"]+":"+tag,
			env["ZOOMIES_RUNNER_DOCKER_REPO"]+":"+tag,
		)
	}
	sort.Strings(refs)

	client := &http.Client{Timeout: 30 * time.Second}
	digests := make(map[string]string, len(refs))
	width := 0
	for _, ref := range refs {
		d, err := resolve(client, ref)
		if err != nil {
			return fmt.Errorf("resolving %s: %w", ref, err)
		}
		digests[ref] = d
		if len(ref) > width {
			width = len(ref)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Every image %s deploys, and the digest its tag resolved to.\n", release)
	b.WriteString("#\n")
	b.WriteString("# Generated by `make marketplace-lock`; do not edit. Each line is one image\n")
	b.WriteString("# reference and the digest it pointed at when this release was locked, so a\n")
	b.WriteString("# deployment can be audited against what was published rather than against\n")
	b.WriteString("# whatever the tag means today.\n#\n")
	b.WriteString("# The runner images are here for that audit, not because the bootstrap picks\n")
	b.WriteString("# one: a controller resolves its runners from its own build tag, so pinning\n")
	b.WriteString("# the controller pins every line below with it.\n\n")
	for _, ref := range refs {
		fmt.Fprintf(&b, "%-*s  %s\n", width, ref, digests[ref])
	}
	return os.WriteFile(filepath.Join(dir, lockFile), []byte(b.String()), 0o644)
}

// resolve asks the registry what a tag points at, without pulling anything.
// GHCR wants a token even for a public repository, and hands one out for the
// asking; the digest is the header the registry answers a manifest request
// with, which is exactly the value `docker pull` would pin.
func resolve(client *http.Client, ref string) (string, error) {
	host, repo, tag, err := split(ref)
	if err != nil {
		return "", err
	}
	token, err := pullToken(client, host, repo)
	if err != nil {
		return "", err
	}
	req, err := http.NewRequest(http.MethodHead, "https://"+registryHost(host)+"/v2/"+repo+"/manifests/"+tag, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", manifestTypes)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("the registry answered %s", resp.Status)
	}
	d := resp.Header.Get("Docker-Content-Digest")
	if !strings.HasPrefix(d, "sha256:") {
		return "", fmt.Errorf("the registry returned no digest")
	}
	return d, nil
}

// split breaks a reference into the registry it lives on, the repository path
// that registry knows it by, and the tag. Docker Hub is the awkward one: its
// references carry no host at all, official images live under an implied
// library/ prefix, and its API is on a different name from its references.
func split(ref string) (host, repo, tag string, err error) {
	rest := ref
	host = "docker.io"
	if i := strings.Index(ref, "/"); i >= 0 && strings.Contains(ref[:i], ".") {
		host, rest = ref[:i], ref[i+1:]
	}
	repo, tag, ok := strings.Cut(rest, ":")
	if !ok {
		return "", "", "", fmt.Errorf("%q names no tag", ref)
	}
	if host == "docker.io" && !strings.Contains(repo, "/") {
		repo = "library/" + repo
	}
	return host, repo, tag, nil
}

// registryHost is where the API lives, which is not always where references say
// the image does.
func registryHost(host string) string {
	if host == "docker.io" {
		return "registry-1.docker.io"
	}
	return host
}

// pullToken asks for anonymous pull access. Both registries hand one out for
// the asking on a public repository; neither serves a manifest without it.
func pullToken(client *http.Client, host, repo string) (string, error) {
	authURL := "https://" + host + "/token?scope=repository:" + repo + ":pull&service=" + host
	if host == "docker.io" {
		authURL = "https://auth.docker.io/token?scope=repository:" + repo + ":pull&service=registry.docker.io"
	}
	resp, err := client.Get(authURL)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", err
	}
	var out struct {
		Token string `json:"token"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		return "", fmt.Errorf("reading the registry's token: %w", err)
	}
	if out.Token == "" {
		return "", fmt.Errorf("the registry issued no token for %s", repo)
	}
	return out.Token, nil
}

// readEnv reads the KEY=value lines of release.env. It is deliberately not a
// shell: the file is sourced by the bootstrap, so anything that needed quoting
// or expansion to be understood here would be a trap there.
func readEnv(path string) (map[string]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("%s: %q is not KEY=value", path, line)
		}
		out[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	return out, nil
}

// stripDigest turns a tag-and-digest reference back into the tag alone, which
// is the question the registry answers.
func stripDigest(ref string) string {
	if i := strings.Index(ref, "@"); i >= 0 {
		return ref[:i]
	}
	return ref
}
