//go:build ignore

// Command gen_runner_digests writes runner_digests.go from the digests GitHub
// publishes for an actions/runner release.
//
// The process backend refuses to install a runner archive it cannot verify,
// so the release Zoomies pins by default has to ship with its digests. Every
// actions/runner release lists them in its notes, between HTML comments of the
// form <!-- BEGIN SHA linux-x64 --> ... <!-- END SHA linux-x64 -->, and this
// command copies the ones for the platforms the process backend supports into
// Go source. The version bump workflow runs it so the table cannot lag the
// version.
//
// Run it from the repository root, with the version DefaultRunnerVersion pins:
//
//	go run internal/backend/gen_runner_digests.go 2.337.0
//
// -body reads a saved copy of the release notes instead of asking GitHub,
// for a host without access to api.github.com.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
)

const target = "internal/backend/runner_digests.go"

// platforms are the archives runnerAsset in process.go can name.
var platforms = []string{"linux-x64", "linux-arm64", "linux-arm", "osx-x64", "osx-arm64"}

var shaBlock = regexp.MustCompile(`<!-- BEGIN SHA ([A-Za-z0-9-]+) -->\s*([0-9a-fA-F]{64})\s*<!-- END SHA `)

func main() {
	bodyFile := flag.String("body", "", "a file holding the release notes, instead of fetching them")
	flag.Parse()
	if flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: go run internal/backend/gen_runner_digests.go [-body notes.md] <version>")
		os.Exit(2)
	}
	version := strings.TrimPrefix(flag.Arg(0), "v")

	var body string
	var err error
	if *bodyFile != "" {
		body, err = readFile(*bodyFile)
	} else {
		body, err = fetchReleaseBody(version)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	found := map[string]string{}
	for _, m := range shaBlock.FindAllStringSubmatch(body, -1) {
		found[m[1]] = strings.ToLower(m[2])
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen_runner_digests.go; DO NOT EDIT.\n//\n")
	fmt.Fprintf(&b, "// Regenerate after bumping DefaultRunnerVersion:\n//\n")
	fmt.Fprintf(&b, "//\tgo run internal/backend/gen_runner_digests.go %s\n\n", version)
	fmt.Fprintf(&b, "package backend\n\n")
	fmt.Fprintf(&b, "// knownRunnerSHA256 holds the SHA-256 of every actions/runner archive the\n")
	fmt.Fprintf(&b, "// process backend can install for DefaultRunnerVersion, keyed\n")
	fmt.Fprintf(&b, "// \"<version>/<asset file name>\". The values are the ones GitHub publishes in\n")
	fmt.Fprintf(&b, "// the release notes, so a download that does not match them is refused rather\n")
	fmt.Fprintf(&b, "// than executed.\n")
	fmt.Fprintf(&b, "var knownRunnerSHA256 = map[string]string{\n")
	keys := make([]string, 0, len(platforms))
	width := 0
	for _, p := range platforms {
		if _, ok := found[p]; !ok {
			fmt.Fprintf(os.Stderr, "the release notes for %s carry no SHA-256 for %s\n", version, p)
			os.Exit(1)
		}
		k := fmt.Sprintf("%s/actions-runner-%s-%s.tar.gz", version, p, version)
		keys = append(keys, k)
		width = max(width, len(k))
	}
	sort.Strings(keys)
	for _, k := range keys {
		platform := strings.TrimSuffix(strings.TrimPrefix(k, version+"/actions-runner-"), "-"+version+".tar.gz")
		fmt.Fprintf(&b, "\t%-*s %q,\n", width+3, fmt.Sprintf("%q:", k), found[platform])
	}
	fmt.Fprintf(&b, "}\n")

	if err := os.WriteFile(target, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s for actions/runner %s (%d archives)\n", target, version, len(keys))
}

func readFile(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// fetchReleaseBody asks GitHub for the release notes. GITHUB_TOKEN, when set,
// lifts the anonymous rate limit, which matters in a workflow.
func fetchReleaseBody(version string) (string, error) {
	req, err := http.NewRequest(http.MethodGet, "https://api.github.com/repos/actions/runner/releases/tags/v"+version, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	if tok := os.Getenv("GITHUB_TOKEN"); tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("fetching the v%s release: %s", version, resp.Status)
	}
	var release struct {
		Body string `json:"body"`
	}
	if err := json.NewDecoder(io.LimitReader(resp.Body, 4<<20)).Decode(&release); err != nil {
		return "", err
	}
	return release.Body, nil
}
