// Code generated by gen_runner_digests.go; DO NOT EDIT.
//
// Regenerate after bumping DefaultRunnerVersion:
//
//	go run internal/backend/gen_runner_digests.go 2.337.0

package backend

// knownRunnerSHA256 holds the SHA-256 of every actions/runner archive the
// process backend can install for DefaultRunnerVersion, keyed
// "<version>/<asset file name>". The values are the ones GitHub publishes in
// the release notes, so a download that does not match them is refused rather
// than executed.
var knownRunnerSHA256 = map[string]string{
	"2.337.0/actions-runner-linux-arm-2.337.0.tar.gz":   "3ea05289b7f7e1bc9a7bb35e2f738a903e0f757cb27ed32a3ef701404cf6d8e8",
	"2.337.0/actions-runner-linux-arm64-2.337.0.tar.gz": "9b1dc70626422526e3c94767cf024896beb15da5342a3f4819bf2feac13e0393",
	"2.337.0/actions-runner-linux-x64-2.337.0.tar.gz":   "70920811a4f8ad4328818682bca5c6469c1c942fab52448868071d0063816613",
	"2.337.0/actions-runner-osx-arm64-2.337.0.tar.gz":   "5a2cd92908a93d7276a194e1de6008099f3e7946f3f8e14aa7a1a7b4a31fdec2",
	"2.337.0/actions-runner-osx-x64-2.337.0.tar.gz":     "d383f505d7ed041b1873ab68c35dd766fc093f2252330f95bb427be8f2c6dcfc",
}
