# Managed by Zoomies AI Context. Never execute files downloaded from the artifact.
import base64
import hashlib
import json
import os
from pathlib import Path
import re
import urllib.error
import urllib.parse
import urllib.request


def publish(directory, api, repo, token, branch, commit, identity, config_hash):
    def request(method, endpoint, body=None):
        data = None if body is None else json.dumps(body).encode()
        req = urllib.request.Request(api.rstrip('/') + '/repos/' + repo + endpoint, data=data, method=method,
                                     headers={'Authorization': 'Bearer ' + token, 'Accept': 'application/vnd.github+json',
                                              'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28'})
        # Never send credentials through an API redirect.
        class NoRedirect(urllib.request.HTTPRedirectHandler):
            def redirect_request(self, *args):
                return None
        try:
            with urllib.request.build_opener(NoRedirect).open(req, timeout=30) as response:
                return json.load(response)
        except urllib.error.HTTPError as error:
            if error.code == 404 and method == 'GET':
                return None
            raise
    if not re.fullmatch('[0-9a-f]{40}', commit):
        raise ValueError('Source identity missing')
    names = {'snapshot.json', 'manifest.json', 'NOTICE.md'}
    if set(p.name for p in directory.iterdir()) != names:
        raise ValueError('Unexpected artifact files')
    contents = {}
    for name in sorted(names):
        p = directory / name
        if p.is_symlink() or not p.is_file() or p.stat().st_size > 32 << 20:
            raise ValueError('Unsafe artifact file')
        contents[name] = p.read_bytes()
    snapshot = json.loads(contents['snapshot.json'])
    manifest = snapshot['manifest']
    publication = json.loads(contents['manifest.json'])
    if contents['NOTICE.md'] != b'Managed by Zoomies AI Context. Generated by Repomix. Do not edit.\n':
        raise ValueError('Missing managed notice')
    if (manifest['repository'] != identity or manifest['source_branch'] != branch
            or manifest['source_commit'] != commit or manifest['config_hash'] != config_hash
            or manifest['manager'] != 'zoomies' or manifest['generator'] != 'repomix@1.18.1'
            or manifest['schema_version'] != 1 or publication['snapshot_sha256'] != hashlib.sha256(contents['snapshot.json']).hexdigest()):
        raise ValueError('Artifact identity mismatch')
    seen = set()
    total = 0
    files = snapshot['files']
    if not 1 <= len(files) <= 5000:
        raise ValueError('Invalid source count')
    for file in files:
        name, data = file['path'], file['content'].encode()
        parts = name.split('/')
        if (not name or len(name) > 1024 or name.startswith('/') or name in seen
                or any(c in name for c in '\\\x00\r\n:')
                or any(p in ('', '.', '..') or p.lower() in ('.git', 'node_modules', '.zoomies') or p.lower().startswith('.env') for p in parts)
                or name.lower().endswith(('.pem', '.key', '.p12', '.pfx', '.db', '.sqlite', '.sqlite3'))
                or len(data) > 1 << 20 or b'\0' in data or hashlib.sha256(data).hexdigest() != file['sha256']):
            raise ValueError('Unsafe source or corrupt hash')
        seen.add(name)
        total += len(data)
    if total > 24 << 20:
        raise ValueError('Source exceeds limit')
    ref = '/git/ref/heads/' + urllib.parse.quote(branch, safe='')
    if request('GET', ref)['object']['sha'] != commit:
        raise ValueError('Source was superseded; generate its latest commit')
    output_ref = '/git/ref/heads/zoomies-ai-context'
    existing = request('GET', output_ref)
    parent = None
    if existing:
        parent = existing['object']['sha']
        old = request('GET', '/contents/.zoomies/ai-context/NOTICE.md?ref=' + parent)
        if not old or old.get('encoding') != 'base64' or base64.b64decode(old['content']) != contents['NOTICE.md']:
            raise ValueError('Generated branch has no recognised ownership; review a repair')
        previous = request('GET', '/git/commits/' + parent)
        if not previous['message'].startswith('Publish Zoomies AI Context\n'):
            raise ValueError('Generated branch ownership changed; review a repair')
        old_tree = request('GET', '/git/trees/' + previous['tree']['sha'] + '?recursive=1')
        if old_tree.get('truncated') or {f['path'] for f in old_tree['tree'] if f['type'] != 'tree'} != {'.zoomies/ai-context/' + name for name in names}:
            raise ValueError('Generated branch contains user files; review a repair')
    entries = []
    for name, content in contents.items():
        blob = request('POST', '/git/blobs', {'encoding': 'base64', 'content': base64.b64encode(content).decode()})
        entries.append({'path': '.zoomies/ai-context/' + name, 'mode': '100644', 'type': 'blob', 'sha': blob['sha']})
    tree = request('POST', '/git/trees', {'tree': entries})
    created = request('POST', '/git/commits', {'message': 'Publish Zoomies AI Context\n\nSource: ' + commit,
                      'tree': tree['sha'], 'parents': [parent] if parent else []})
    if request('GET', ref)['object']['sha'] != commit:
        raise ValueError('Source changed before publication; rerun generation')
    if existing:
        # This is a fast-forward from the exact parent read above. A competing
        # publication fails rather than replacing a newer snapshot.
        request('PATCH', '/git/refs/heads/zoomies-ai-context', {'sha': created['sha'], 'force': False})
    else:
        request('POST', '/git/refs', {'ref': 'refs/heads/zoomies-ai-context', 'sha': created['sha']})


if __name__ == '__main__':
    try:
        publish(Path(os.environ['ARTIFACT_DIR']), os.environ['GITHUB_API_URL'], os.environ['GITHUB_REPOSITORY'],
                os.environ['GH_TOKEN'], os.environ['SOURCE_BRANCH'], os.environ['SOURCE_COMMIT'],
                json.loads(os.environ['REPOSITORY_IDENTITY']), os.environ['CONFIG_HASH'])
    except Exception:
        raise SystemExit('Context publication refused. Check GitHub write access, artifact integrity, source freshness and generated branch ownership.')
