# Managed by Zoomies AI Context. Never execute files downloaded from the artifact.
#
# Zoomies-only output: the generated snapshot goes to the controller instead of
# a branch. The only credential is the job's own GitHub Actions OIDC token,
# minted for this run with the controller's upload address as its audience, so
# nothing long-lived sits in the repository and a token cannot be replayed
# against another Zoomies.
import hashlib
import json
import os
from pathlib import Path
import re
import urllib.error
import urllib.parse
import urllib.request


class NoRedirect(urllib.request.HTTPRedirectHandler):
    # A redirect would carry the bearer token somewhere this job never named.
    def redirect_request(self, *args):
        return None


def read_artifact(directory, branch, commit, identity, config_hash):
    if not re.fullmatch('[0-9a-f]{40}', commit):
        raise ValueError('Source identity missing')
    names = {'snapshot.json', 'manifest.json', 'NOTICE.md'}
    if set(p.name for p in directory.iterdir()) != names:
        raise ValueError('Unexpected artifact files')
    contents = {}
    for name in sorted(names):
        p = directory / name
        if p.is_symlink() or not p.is_file() or p.stat().st_size > 32 << 20:
            raise ValueError('Unsafe artifact file')
        contents[name] = p.read_bytes()
    snapshot = json.loads(contents['snapshot.json'])
    manifest = snapshot['manifest']
    publication = json.loads(contents['manifest.json'])
    if contents['NOTICE.md'] != b'Managed by Zoomies AI Context. Generated by Repomix. Do not edit.\n':
        raise ValueError('Missing managed notice')
    if (manifest['repository'] != identity or manifest['source_branch'] != branch
            or manifest['source_commit'] != commit or manifest['config_hash'] != config_hash
            or manifest['manager'] != 'zoomies' or manifest['generator'] != 'repomix@1.18.1'
            or manifest['schema_version'] != 1 or publication['snapshot_sha256'] != hashlib.sha256(contents['snapshot.json']).hexdigest()):
        raise ValueError('Artifact identity mismatch')
    return contents['snapshot.json']


def oidc_token(request_url, request_token, audience, opener):
    if not request_url or not request_token:
        raise ValueError('The upload job needs id-token: write')
    url = request_url + ('&' if '?' in request_url else '?') + 'audience=' + urllib.parse.quote(audience, safe='')
    req = urllib.request.Request(url, headers={'Authorization': 'Bearer ' + request_token, 'Accept': 'application/json'})
    with opener.open(req, timeout=30) as response:
        value = json.load(response).get('value', '')
    if not value:
        raise ValueError('GitHub did not issue an OIDC token')
    return value


def upload(directory, branch, commit, identity, config_hash, upload_url, request_url, request_token, opener=None):
    parsed = urllib.parse.urlsplit(upload_url)
    if parsed.scheme != 'https' or not parsed.netloc or parsed.username or parsed.query or parsed.fragment:
        raise ValueError('The upload address must be an https URL')
    body = read_artifact(directory, branch, commit, identity, config_hash)
    opener = opener or urllib.request.build_opener(NoRedirect)
    token = oidc_token(request_url, request_token, upload_url, opener)
    req = urllib.request.Request(upload_url, data=body, method='POST', headers={
        'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json',
        'X-Zoomies-Snapshot-SHA256': hashlib.sha256(body).hexdigest()})
    try:
        with opener.open(req, timeout=120) as response:
            return response.status
    except urllib.error.HTTPError as error:
        # The controller's message is written for the person reading this log
        # and never carries source, so it is safe to show.
        try:
            message = json.load(error).get('error', {}).get('message', '')
        except Exception:
            message = ''
        raise ValueError('Zoomies refused the upload (HTTP %d): %s' % (error.code, message[:500]))


if __name__ == '__main__':
    try:
        status = upload(Path(os.environ['ARTIFACT_DIR']), os.environ['SOURCE_BRANCH'],
                        os.environ['SOURCE_COMMIT'], json.loads(os.environ['REPOSITORY_IDENTITY']),
                        os.environ['CONFIG_HASH'], os.environ['UPLOAD_URL'],
                        os.environ.get('ACTIONS_ID_TOKEN_REQUEST_URL', ''),
                        os.environ.get('ACTIONS_ID_TOKEN_REQUEST_TOKEN', ''))
        print('Uploaded verified context to Zoomies (HTTP %d).' % status)
    except ValueError as error:
        raise SystemExit(str(error))
    except Exception:
        raise SystemExit('The upload to Zoomies could not complete. Check that the controller is reachable at its upload address.')
